//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UseCircleService140917.CircleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservicedemo.datamatiker-skolen.dk/CircleService.svc", ConfigurationName="CircleService.ICircleService")]
    public interface ICircleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservicedemo.datamatiker-skolen.dk/CircleService.svc/ICircleService/Calc" +
            "Diameter", ReplyAction="http://webservicedemo.datamatiker-skolen.dk/CircleService.svc/ICircleService/Calc" +
            "DiameterResponse")]
        double CalcDiameter(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservicedemo.datamatiker-skolen.dk/CircleService.svc/ICircleService/Calc" +
            "Diameter", ReplyAction="http://webservicedemo.datamatiker-skolen.dk/CircleService.svc/ICircleService/Calc" +
            "DiameterResponse")]
        System.Threading.Tasks.Task<double> CalcDiameterAsync(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservicedemo.datamatiker-skolen.dk/CircleService.svc/ICircleService/Calc" +
            "Circumference", ReplyAction="http://webservicedemo.datamatiker-skolen.dk/CircleService.svc/ICircleService/Calc" +
            "CircumferenceResponse")]
        double CalcCircumference(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservicedemo.datamatiker-skolen.dk/CircleService.svc/ICircleService/Calc" +
            "Circumference", ReplyAction="http://webservicedemo.datamatiker-skolen.dk/CircleService.svc/ICircleService/Calc" +
            "CircumferenceResponse")]
        System.Threading.Tasks.Task<double> CalcCircumferenceAsync(double radius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICircleServiceChannel : UseCircleService140917.CircleService.ICircleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CircleServiceClient : System.ServiceModel.ClientBase<UseCircleService140917.CircleService.ICircleService>, UseCircleService140917.CircleService.ICircleService {
        
        public CircleServiceClient() {
        }
        
        public CircleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CircleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CircleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CircleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalcDiameter(double radius) {
            return base.Channel.CalcDiameter(radius);
        }
        
        public System.Threading.Tasks.Task<double> CalcDiameterAsync(double radius) {
            return base.Channel.CalcDiameterAsync(radius);
        }
        
        public double CalcCircumference(double radius) {
            return base.Channel.CalcCircumference(radius);
        }
        
        public System.Threading.Tasks.Task<double> CalcCircumferenceAsync(double radius) {
            return base.Channel.CalcCircumferenceAsync(radius);
        }
    }
}
